name: Cours4IAPA

on:
  push:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        $vcpkg_root = $(Get-Location).Path
        echo "VCPKG_ROOT=$vcpkg_root" | Out-File -FilePath $env:GITHUB_ENV -Append
        echo "$vcpkg_root" | Out-File -FilePath $env:GITHUB_PATH -Append
        echo ${{ github.workspace }}
        echo ${{ env.BUILD_TYPE }}
      shell: pwsh

    - name: Add dependencies
      run: |
        vcpkg new --application
        vcpkg add port sfml
      shell: cmd

    - name: Configure CMake
      run: |
        cmake -S . -B build `
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} `
          -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"
      shell: pwsh

    - name: Build Project
      run: cmake --build build --config ${{ env.BUILD_TYPE }}
      shell: pwsh

    - name: Run Executable
      working-directory: ${{ github.workspace }}/build/${{ env.BUILD_TYPE }}
      run: |
        echo ${{ github.workspace }}/build/${{ env.BUILD_TYPE }}
        start /b .\Cours4IAPA.exe
        timeout /t 5
        taskkill /f /im Cours4IAPA.exe
      shell: cmd
